<?php
/**
 * ContactsApi
 * PHP version 5
 *
 * @category Class
 * @package  MongooseIM\Admin
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MongooseIM's REST API for backend administration
 *
 * Explore MongooseIM features using our REST API.  If you are familiar with the `mongooseimctl` command, the provided control functionality will seem very similar. The response objects are modeled on the `ejabberd_commands` entries and print-outs from `mongooseimctl`.  Please note that many of the fields such as **username** or **caller** expect a **JID** (jabber identifier, f.e. **alice@wonderland.com**). There are two types of **JIDs**:   * **bare JID** - consists of **username** and **domain name** (XMPP host, usually the one set in your `ejabberd.cfg` file).   * **full JID** - is a **bare JID** with online user's resource to uniquely identify user's connection (f.e. **alice@wonderland.com/resource**).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MongooseIM\Admin\Api;

use \MongooseIM\Admin\Configuration;
use \MongooseIM\Admin\ApiClient;
use \MongooseIM\Admin\ApiException;
use \MongooseIM\Admin\ObjectSerializer;

/**
 * ContactsApi Class Doc Comment
 *
 * @category Class
 * @package  MongooseIM\Admin
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactsApi
{

    /**
     * API Client
     *
     * @var \MongooseIM\Admin\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \MongooseIM\Admin\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\MongooseIM\Admin\ApiClient $apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://localhost:8088/api');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \MongooseIM\Admin\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \MongooseIM\Admin\ApiClient $apiClient set the API client
     *
     * @return ContactsApi
     */
    public function setApiClient(\MongooseIM\Admin\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation contactsUserContactDelete
     *
     * 
     *
     * @param string $user  (required)
     * @param string $contact  (required)
     * @return void
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function contactsUserContactDelete($user, $contact)
    {
        list($response) = $this->contactsUserContactDeleteWithHttpInfo($user, $contact);
        return $response;
    }

    /**
     * Operation contactsUserContactDeleteWithHttpInfo
     *
     * 
     *
     * @param string $user  (required)
     * @param string $contact  (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function contactsUserContactDeleteWithHttpInfo($user, $contact)
    {
        // verify the required parameter 'user' is set
        if ($user === null) {
            throw new \InvalidArgumentException('Missing the required parameter $user when calling contactsUserContactDelete');
        }
        // verify the required parameter 'contact' is set
        if ($contact === null) {
            throw new \InvalidArgumentException('Missing the required parameter $contact when calling contactsUserContactDelete');
        }
        // parse inputs
        $resourcePath = "/contacts/{user}/{contact}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($user !== null) {
            $resourcePath = str_replace(
                "{" . "user" . "}",
                $this->apiClient->getSerializer()->toPathValue($user),
                $resourcePath
            );
        }
        // path params
        if ($contact !== null) {
            $resourcePath = str_replace(
                "{" . "contact" . "}",
                $this->apiClient->getSerializer()->toPathValue($contact),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/contacts/{user}/{contact}'
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation contactsUserContactManagePut
     *
     * 
     *
     * @param string $user  (required)
     * @param string $contact  (required)
     * @param string $action  (required)
     * @return void
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function contactsUserContactManagePut($user, $contact, $action)
    {
        list($response) = $this->contactsUserContactManagePutWithHttpInfo($user, $contact, $action);
        return $response;
    }

    /**
     * Operation contactsUserContactManagePutWithHttpInfo
     *
     * 
     *
     * @param string $user  (required)
     * @param string $contact  (required)
     * @param string $action  (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function contactsUserContactManagePutWithHttpInfo($user, $contact, $action)
    {
        // verify the required parameter 'user' is set
        if ($user === null) {
            throw new \InvalidArgumentException('Missing the required parameter $user when calling contactsUserContactManagePut');
        }
        // verify the required parameter 'contact' is set
        if ($contact === null) {
            throw new \InvalidArgumentException('Missing the required parameter $contact when calling contactsUserContactManagePut');
        }
        // verify the required parameter 'action' is set
        if ($action === null) {
            throw new \InvalidArgumentException('Missing the required parameter $action when calling contactsUserContactManagePut');
        }
        // parse inputs
        $resourcePath = "/contacts/{user}/{contact}/manage";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($user !== null) {
            $resourcePath = str_replace(
                "{" . "user" . "}",
                $this->apiClient->getSerializer()->toPathValue($user),
                $resourcePath
            );
        }
        // path params
        if ($contact !== null) {
            $resourcePath = str_replace(
                "{" . "contact" . "}",
                $this->apiClient->getSerializer()->toPathValue($contact),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($action)) {
            $_tempBody = $action;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/contacts/{user}/{contact}/manage'
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation contactsUserContactPut
     *
     * 
     *
     * @param string $user  (required)
     * @param string $contact  (required)
     * @param string $action  (required)
     * @return void
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function contactsUserContactPut($user, $contact, $action)
    {
        list($response) = $this->contactsUserContactPutWithHttpInfo($user, $contact, $action);
        return $response;
    }

    /**
     * Operation contactsUserContactPutWithHttpInfo
     *
     * 
     *
     * @param string $user  (required)
     * @param string $contact  (required)
     * @param string $action  (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function contactsUserContactPutWithHttpInfo($user, $contact, $action)
    {
        // verify the required parameter 'user' is set
        if ($user === null) {
            throw new \InvalidArgumentException('Missing the required parameter $user when calling contactsUserContactPut');
        }
        // verify the required parameter 'contact' is set
        if ($contact === null) {
            throw new \InvalidArgumentException('Missing the required parameter $contact when calling contactsUserContactPut');
        }
        // verify the required parameter 'action' is set
        if ($action === null) {
            throw new \InvalidArgumentException('Missing the required parameter $action when calling contactsUserContactPut');
        }
        // parse inputs
        $resourcePath = "/contacts/{user}/{contact}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($user !== null) {
            $resourcePath = str_replace(
                "{" . "user" . "}",
                $this->apiClient->getSerializer()->toPathValue($user),
                $resourcePath
            );
        }
        // path params
        if ($contact !== null) {
            $resourcePath = str_replace(
                "{" . "contact" . "}",
                $this->apiClient->getSerializer()->toPathValue($contact),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($action)) {
            $_tempBody = $action;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/contacts/{user}/{contact}'
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation contactsUserGet
     *
     * 
     *
     * @param string $user User&#39;s JID (f.e. alice@wonderland.lit) (required)
     * @return \MongooseIM\Admin\Models\ContactDetails[]
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function contactsUserGet($user)
    {
        list($response) = $this->contactsUserGetWithHttpInfo($user);
        return $response;
    }

    /**
     * Operation contactsUserGetWithHttpInfo
     *
     * 
     *
     * @param string $user User&#39;s JID (f.e. alice@wonderland.lit) (required)
     * @return Array of \MongooseIM\Admin\Models\ContactDetails[], HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function contactsUserGetWithHttpInfo($user)
    {
        // verify the required parameter 'user' is set
        if ($user === null) {
            throw new \InvalidArgumentException('Missing the required parameter $user when calling contactsUserGet');
        }
        // parse inputs
        $resourcePath = "/contacts/{user}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($user !== null) {
            $resourcePath = str_replace(
                "{" . "user" . "}",
                $this->apiClient->getSerializer()->toPathValue($user),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\MongooseIM\Admin\Models\ContactDetails[]',
                '/contacts/{user}'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\MongooseIM\Admin\Models\ContactDetails[]', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\MongooseIM\Admin\Models\ContactDetails[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation contactsUserPost
     *
     * 
     *
     * @param \MongooseIM\Admin\Models\Addcontact $contact  (required)
     * @return void
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function contactsUserPost($contact)
    {
        list($response) = $this->contactsUserPostWithHttpInfo($contact);
        return $response;
    }

    /**
     * Operation contactsUserPostWithHttpInfo
     *
     * 
     *
     * @param \MongooseIM\Admin\Models\Addcontact $contact  (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function contactsUserPostWithHttpInfo($contact)
    {
        // verify the required parameter 'contact' is set
        if ($contact === null) {
            throw new \InvalidArgumentException('Missing the required parameter $contact when calling contactsUserPost');
        }
        // parse inputs
        $resourcePath = "/contacts/{user}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($contact)) {
            $_tempBody = $contact;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/contacts/{user}'
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

}
