<?php
/**
 * MUClightManagementApi
 * PHP version 5
 *
 * @category Class
 * @package  MongooseIM\Admin
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MongooseIM's REST API for backend administration
 *
 * Explore MongooseIM features using our REST API.  If you are familiar with the `mongooseimctl` command, the provided control functionality will seem very similar. The response objects are modeled on the `ejabberd_commands` entries and print-outs from `mongooseimctl`.  Please note that many of the fields such as **username** or **caller** expect a **JID** (jabber identifier, f.e. **alice@wonderland.com**). There are two types of **JIDs**:   * **bare JID** - consists of **username** and **domain name** (XMPP host, usually the one set in your `ejabberd.cfg` file).   * **full JID** - is a **bare JID** with online user's resource to uniquely identify user's connection (f.e. **alice@wonderland.com/resource**).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MongooseIM\Admin\Api;

use \MongooseIM\Admin\Configuration;
use \MongooseIM\Admin\ApiClient;
use \MongooseIM\Admin\ApiException;
use \MongooseIM\Admin\ObjectSerializer;

/**
 * MUClightManagementApi Class Doc Comment
 *
 * @category Class
 * @package  MongooseIM\Admin
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MUClightManagementApi
{

    /**
     * API Client
     *
     * @var \MongooseIM\Admin\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \MongooseIM\Admin\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\MongooseIM\Admin\ApiClient $apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://localhost:8088/api');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \MongooseIM\Admin\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \MongooseIM\Admin\ApiClient $apiClient set the API client
     *
     * @return MUClightManagementApi
     */
    public function setApiClient(\MongooseIM\Admin\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation mucLightsXMPPHostPost
     *
     * 
     *
     * @param string $xmpp_host The XMPP host served by the server. (required)
     * @param \MongooseIM\Admin\Models\RoomDetails1 $room_details Details for the room to be created (required)
     * @return string
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function mucLightsXMPPHostPost($xmpp_host, $room_details)
    {
        list($response) = $this->mucLightsXMPPHostPostWithHttpInfo($xmpp_host, $room_details);
        return $response;
    }

    /**
     * Operation mucLightsXMPPHostPostWithHttpInfo
     *
     * 
     *
     * @param string $xmpp_host The XMPP host served by the server. (required)
     * @param \MongooseIM\Admin\Models\RoomDetails1 $room_details Details for the room to be created (required)
     * @return Array of string, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function mucLightsXMPPHostPostWithHttpInfo($xmpp_host, $room_details)
    {
        // verify the required parameter 'xmpp_host' is set
        if ($xmpp_host === null) {
            throw new \InvalidArgumentException('Missing the required parameter $xmpp_host when calling mucLightsXMPPHostPost');
        }
        // verify the required parameter 'room_details' is set
        if ($room_details === null) {
            throw new \InvalidArgumentException('Missing the required parameter $room_details when calling mucLightsXMPPHostPost');
        }
        // parse inputs
        $resourcePath = "/muc-lights/{XMPPHost}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($xmpp_host !== null) {
            $resourcePath = str_replace(
                "{" . "XMPPHost" . "}",
                $this->apiClient->getSerializer()->toPathValue($xmpp_host),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($room_details)) {
            $_tempBody = $room_details;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                'string',
                '/muc-lights/{XMPPHost}'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation mucLightsXMPPHostPut
     *
     * 
     *
     * @param string $xmpp_host The XMPP host served by the server. (required)
     * @param \MongooseIM\Admin\Models\RoomDetails $room_details Details for the room to be created (including ID) (required)
     * @return string
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function mucLightsXMPPHostPut($xmpp_host, $room_details)
    {
        list($response) = $this->mucLightsXMPPHostPutWithHttpInfo($xmpp_host, $room_details);
        return $response;
    }

    /**
     * Operation mucLightsXMPPHostPutWithHttpInfo
     *
     * 
     *
     * @param string $xmpp_host The XMPP host served by the server. (required)
     * @param \MongooseIM\Admin\Models\RoomDetails $room_details Details for the room to be created (including ID) (required)
     * @return Array of string, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function mucLightsXMPPHostPutWithHttpInfo($xmpp_host, $room_details)
    {
        // verify the required parameter 'xmpp_host' is set
        if ($xmpp_host === null) {
            throw new \InvalidArgumentException('Missing the required parameter $xmpp_host when calling mucLightsXMPPHostPut');
        }
        // verify the required parameter 'room_details' is set
        if ($room_details === null) {
            throw new \InvalidArgumentException('Missing the required parameter $room_details when calling mucLightsXMPPHostPut');
        }
        // parse inputs
        $resourcePath = "/muc-lights/{XMPPHost}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($xmpp_host !== null) {
            $resourcePath = str_replace(
                "{" . "XMPPHost" . "}",
                $this->apiClient->getSerializer()->toPathValue($xmpp_host),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($room_details)) {
            $_tempBody = $room_details;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                'string',
                '/muc-lights/{XMPPHost}'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation mucLightsXMPPMUCHostRoomNameMessagesPost
     *
     * 
     *
     * @param string $xmppmuc_host The XMPP host of the muc service. (required)
     * @param string $room_name The MUC Light room&#39;s **name** (i.e. **not** the room&#39;s JID) (required)
     * @param \MongooseIM\Admin\Models\ChatMessage $chat_message The message details (required)
     * @return void
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function mucLightsXMPPMUCHostRoomNameMessagesPost($xmppmuc_host, $room_name, $chat_message)
    {
        list($response) = $this->mucLightsXMPPMUCHostRoomNameMessagesPostWithHttpInfo($xmppmuc_host, $room_name, $chat_message);
        return $response;
    }

    /**
     * Operation mucLightsXMPPMUCHostRoomNameMessagesPostWithHttpInfo
     *
     * 
     *
     * @param string $xmppmuc_host The XMPP host of the muc service. (required)
     * @param string $room_name The MUC Light room&#39;s **name** (i.e. **not** the room&#39;s JID) (required)
     * @param \MongooseIM\Admin\Models\ChatMessage $chat_message The message details (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function mucLightsXMPPMUCHostRoomNameMessagesPostWithHttpInfo($xmppmuc_host, $room_name, $chat_message)
    {
        // verify the required parameter 'xmppmuc_host' is set
        if ($xmppmuc_host === null) {
            throw new \InvalidArgumentException('Missing the required parameter $xmppmuc_host when calling mucLightsXMPPMUCHostRoomNameMessagesPost');
        }
        // verify the required parameter 'room_name' is set
        if ($room_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $room_name when calling mucLightsXMPPMUCHostRoomNameMessagesPost');
        }
        // verify the required parameter 'chat_message' is set
        if ($chat_message === null) {
            throw new \InvalidArgumentException('Missing the required parameter $chat_message when calling mucLightsXMPPMUCHostRoomNameMessagesPost');
        }
        // parse inputs
        $resourcePath = "/muc-lights/{XMPPMUCHost}/{roomName}/messages";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($xmppmuc_host !== null) {
            $resourcePath = str_replace(
                "{" . "XMPPMUCHost" . "}",
                $this->apiClient->getSerializer()->toPathValue($xmppmuc_host),
                $resourcePath
            );
        }
        // path params
        if ($room_name !== null) {
            $resourcePath = str_replace(
                "{" . "roomName" . "}",
                $this->apiClient->getSerializer()->toPathValue($room_name),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($chat_message)) {
            $_tempBody = $chat_message;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/muc-lights/{XMPPMUCHost}/{roomName}/messages'
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation mucLightsXMPPMUCHostRoomNameParticipantsPost
     *
     * 
     *
     * @param string $xmppmuc_host The XMPP host of the muc service. (required)
     * @param string $room_name The MUC Light room&#39;s **name** (i.e. **not** the room&#39;s JID) (required)
     * @param \MongooseIM\Admin\Models\Invite $invite The invite itself (required)
     * @return void
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function mucLightsXMPPMUCHostRoomNameParticipantsPost($xmppmuc_host, $room_name, $invite)
    {
        list($response) = $this->mucLightsXMPPMUCHostRoomNameParticipantsPostWithHttpInfo($xmppmuc_host, $room_name, $invite);
        return $response;
    }

    /**
     * Operation mucLightsXMPPMUCHostRoomNameParticipantsPostWithHttpInfo
     *
     * 
     *
     * @param string $xmppmuc_host The XMPP host of the muc service. (required)
     * @param string $room_name The MUC Light room&#39;s **name** (i.e. **not** the room&#39;s JID) (required)
     * @param \MongooseIM\Admin\Models\Invite $invite The invite itself (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function mucLightsXMPPMUCHostRoomNameParticipantsPostWithHttpInfo($xmppmuc_host, $room_name, $invite)
    {
        // verify the required parameter 'xmppmuc_host' is set
        if ($xmppmuc_host === null) {
            throw new \InvalidArgumentException('Missing the required parameter $xmppmuc_host when calling mucLightsXMPPMUCHostRoomNameParticipantsPost');
        }
        // verify the required parameter 'room_name' is set
        if ($room_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $room_name when calling mucLightsXMPPMUCHostRoomNameParticipantsPost');
        }
        // verify the required parameter 'invite' is set
        if ($invite === null) {
            throw new \InvalidArgumentException('Missing the required parameter $invite when calling mucLightsXMPPMUCHostRoomNameParticipantsPost');
        }
        // parse inputs
        $resourcePath = "/muc-lights/{XMPPMUCHost}/{roomName}/participants";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($xmppmuc_host !== null) {
            $resourcePath = str_replace(
                "{" . "XMPPMUCHost" . "}",
                $this->apiClient->getSerializer()->toPathValue($xmppmuc_host),
                $resourcePath
            );
        }
        // path params
        if ($room_name !== null) {
            $resourcePath = str_replace(
                "{" . "roomName" . "}",
                $this->apiClient->getSerializer()->toPathValue($room_name),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($invite)) {
            $_tempBody = $invite;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/muc-lights/{XMPPMUCHost}/{roomName}/participants'
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

    /**
     * Operation mucLightsXMPPMUCHostRoomNameUserManagementDelete
     *
     * 
     *
     * @param string $xmppmuc_host The XMPP host of the muc service. (required)
     * @param string $room_name The MUC Light room&#39;s **name** (i.e. **not** the room&#39;s JID) (required)
     * @param string $error_unknown User&#39;s JID (f.e. alice@wonderland.lit) (required)
     * @return void
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function mucLightsXMPPMUCHostRoomNameUserManagementDelete($xmppmuc_host, $room_name, $error_unknown)
    {
        list($response) = $this->mucLightsXMPPMUCHostRoomNameUserManagementDeleteWithHttpInfo($xmppmuc_host, $room_name, $error_unknown);
        return $response;
    }

    /**
     * Operation mucLightsXMPPMUCHostRoomNameUserManagementDeleteWithHttpInfo
     *
     * 
     *
     * @param string $xmppmuc_host The XMPP host of the muc service. (required)
     * @param string $room_name The MUC Light room&#39;s **name** (i.e. **not** the room&#39;s JID) (required)
     * @param string $error_unknown User&#39;s JID (f.e. alice@wonderland.lit) (required)
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function mucLightsXMPPMUCHostRoomNameUserManagementDeleteWithHttpInfo($xmppmuc_host, $room_name, $error_unknown)
    {
        // verify the required parameter 'xmppmuc_host' is set
        if ($xmppmuc_host === null) {
            throw new \InvalidArgumentException('Missing the required parameter $xmppmuc_host when calling mucLightsXMPPMUCHostRoomNameUserManagementDelete');
        }
        // verify the required parameter 'room_name' is set
        if ($room_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $room_name when calling mucLightsXMPPMUCHostRoomNameUserManagementDelete');
        }
        // verify the required parameter 'error_unknown' is set
        if ($error_unknown === null) {
            throw new \InvalidArgumentException('Missing the required parameter $error_unknown when calling mucLightsXMPPMUCHostRoomNameUserManagementDelete');
        }
        // parse inputs
        $resourcePath = "/muc-lights/{XMPPMUCHost}/{roomName}/{user}/management";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($xmppmuc_host !== null) {
            $resourcePath = str_replace(
                "{" . "XMPPMUCHost" . "}",
                $this->apiClient->getSerializer()->toPathValue($xmppmuc_host),
                $resourcePath
            );
        }
        // path params
        if ($room_name !== null) {
            $resourcePath = str_replace(
                "{" . "roomName" . "}",
                $this->apiClient->getSerializer()->toPathValue($room_name),
                $resourcePath
            );
        }
        // path params
        if ($error_unknown !== null) {
            $resourcePath = str_replace(
                "{" . "" . "}",
                $this->apiClient->getSerializer()->toPathValue($error_unknown),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                null,
                '/muc-lights/{XMPPMUCHost}/{roomName}/{user}/management'
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }

}
