<?php
/**
 * SessionManagementApi
 * PHP version 5
 *
 * @category Class
 * @package  MongooseIM\Admin
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MongooseIM's REST API for backend administration
 *
 * Explore MongooseIM features using our REST API.  If you are familiar with the `mongooseimctl` command, the provided control functionality will seem very similar. The response objects are modeled on the `ejabberd_commands` entries and print-outs from `mongooseimctl`.  Please note that many of the fields such as **username** or **caller** expect a **JID** (jabber identifier, f.e. **alice@wonderland.com**). There are two types of **JIDs**:   * **bare JID** - consists of **username** and **domain name** (XMPP host, usually the one set in your `ejabberd.cfg` file).   * **full JID** - is a **bare JID** with online user's resource to uniquely identify user's connection (f.e. **alice@wonderland.com/resource**).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MongooseIM\Admin\Api;

use \MongooseIM\Admin\Configuration;
use \MongooseIM\Admin\ApiClient;
use \MongooseIM\Admin\ApiException;
use \MongooseIM\Admin\ObjectSerializer;

/**
 * SessionManagementApi Class Doc Comment
 *
 * @category Class
 * @package  MongooseIM\Admin
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SessionManagementApi
{

    /**
     * API Client
     *
     * @var \MongooseIM\Admin\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \MongooseIM\Admin\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\MongooseIM\Admin\ApiClient $apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://localhost:8088/api');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \MongooseIM\Admin\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \MongooseIM\Admin\ApiClient $apiClient set the API client
     *
     * @return SessionManagementApi
     */
    public function setApiClient(\MongooseIM\Admin\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation sessionsXMPPHostGet
     *
     * 
     *
     * @param string $xmpp_host The XMPP host served by the server. (required)
     * @return string[]
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function sessionsXMPPHostGet($xmpp_host)
    {
        list($response) = $this->sessionsXMPPHostGetWithHttpInfo($xmpp_host);
        return $response;
    }

    /**
     * Operation sessionsXMPPHostGetWithHttpInfo
     *
     * 
     *
     * @param string $xmpp_host The XMPP host served by the server. (required)
     * @return Array of string[], HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function sessionsXMPPHostGetWithHttpInfo($xmpp_host)
    {
        // verify the required parameter 'xmpp_host' is set
        if ($xmpp_host === null) {
            throw new \InvalidArgumentException('Missing the required parameter $xmpp_host when calling sessionsXMPPHostGet');
        }
        // parse inputs
        $resourcePath = "/sessions/{XMPPHost}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($xmpp_host !== null) {
            $resourcePath = str_replace(
                "{" . "XMPPHost" . "}",
                $this->apiClient->getSerializer()->toPathValue($xmpp_host),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                'string[]',
                '/sessions/{XMPPHost}'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, 'string[]', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation sessionsXMPPHostUsernameResourceDelete
     *
     * 
     *
     * @param string $xmpp_host The XMPP host served by the server. (required)
     * @param string $username The leading part of a user&#39;s JID. (required)
     * @param string $resource A resource name for the given user. (required)
     * @return string
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function sessionsXMPPHostUsernameResourceDelete($xmpp_host, $username, $resource)
    {
        list($response) = $this->sessionsXMPPHostUsernameResourceDeleteWithHttpInfo($xmpp_host, $username, $resource);
        return $response;
    }

    /**
     * Operation sessionsXMPPHostUsernameResourceDeleteWithHttpInfo
     *
     * 
     *
     * @param string $xmpp_host The XMPP host served by the server. (required)
     * @param string $username The leading part of a user&#39;s JID. (required)
     * @param string $resource A resource name for the given user. (required)
     * @return Array of string, HTTP status code, HTTP response headers (array of strings)
     * @throws \MongooseIM\Admin\ApiException on non-2xx response
     */
    public function sessionsXMPPHostUsernameResourceDeleteWithHttpInfo($xmpp_host, $username, $resource)
    {
        // verify the required parameter 'xmpp_host' is set
        if ($xmpp_host === null) {
            throw new \InvalidArgumentException('Missing the required parameter $xmpp_host when calling sessionsXMPPHostUsernameResourceDelete');
        }
        // verify the required parameter 'username' is set
        if ($username === null) {
            throw new \InvalidArgumentException('Missing the required parameter $username when calling sessionsXMPPHostUsernameResourceDelete');
        }
        // verify the required parameter 'resource' is set
        if ($resource === null) {
            throw new \InvalidArgumentException('Missing the required parameter $resource when calling sessionsXMPPHostUsernameResourceDelete');
        }
        // parse inputs
        $resourcePath = "/sessions/{XMPPHost}/{username}/{resource}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        // path params
        if ($xmpp_host !== null) {
            $resourcePath = str_replace(
                "{" . "XMPPHost" . "}",
                $this->apiClient->getSerializer()->toPathValue($xmpp_host),
                $resourcePath
            );
        }
        // path params
        if ($username !== null) {
            $resourcePath = str_replace(
                "{" . "username" . "}",
                $this->apiClient->getSerializer()->toPathValue($username),
                $resourcePath
            );
        }
        // path params
        if ($resource !== null) {
            $resourcePath = str_replace(
                "{" . "resource" . "}",
                $this->apiClient->getSerializer()->toPathValue($resource),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams,
                'string',
                '/sessions/{XMPPHost}/{username}/{resource}'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 204:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

}
